// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ttuMc-mueXPrxxou1lS3Np0H6vrZHVA',
    appId: '1:767760875619:web:c4e9db50fa04a80c4db856',
    messagingSenderId: '767760875619',
    projectId: 'mendmee-d52b0',
    authDomain: 'mendmee-d52b0.firebaseapp.com',
    storageBucket: 'mendmee-d52b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTUHEigrvDFsajlntrMWwHy76BRA7JU0',
    appId: '1:767760875619:android:ede5cbbb146f684b4db856',
    messagingSenderId: '767760875619',
    projectId: 'mendmee-d52b0',
    storageBucket: 'mendmee-d52b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbb_9HCpXYW0LMi8Z3BAEEEp7sABtUTSM',
    appId: '1:767760875619:ios:e5597cfdf8b0d7984db856',
    messagingSenderId: '767760875619',
    projectId: 'mendmee-d52b0',
    storageBucket: 'mendmee-d52b0.appspot.com',
    androidClientId:
        '767760875619-jfe4nskfvi5o8p6cpadl904jnkqch9el.apps.googleusercontent.com',
    iosBundleId: 'com.mendmee.serviceProvidersideapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbb_9HCpXYW0LMi8Z3BAEEEp7sABtUTSM',
    appId: '1:767760875619:ios:e5597cfdf8b0d7984db856',
    messagingSenderId: '767760875619',
    projectId: 'mendmee-d52b0',
    storageBucket: 'mendmee-d52b0.appspot.com',
    androidClientId:
        '767760875619-jfe4nskfvi5o8p6cpadl904jnkqch9el.apps.googleusercontent.com',
    iosBundleId: 'com.mendmee.serviceProvidersideapp',
  );
}
